###  VISUALIZATION
/vis/open   OGL
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
/vis/scene/endOfEventAction   accumulate 0
/vis/viewer/zoom 1.5
#  Theta controls rot around up-down axis, 0 looking down z axis
#  Phi controls rot around horizontal axis
/vis/viewer/set/viewpointThetaPhi 70 30
/vis/viewer/panTo -100 0 mm
#  filter out photons from visualisation for clarity
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add e-
